### ISSUE TITLE
Example for one classification task such as sentiment

### ISSUE THREAD

**Issue by aykutfirat** [salesforce/cove#1]
Thanks for releasing the Cove vectors. That is very helpful. Do you have any plans to release one of the examples presented in the paper (such as sentiment) in pytorch as well?

**Comment by bmccann** [comment]
yes! I'm working on building them on top of more standard data processing tools like [torchtext](https://github.com/pytorch/text/tree/master/torchtext) instead of my own custom setup. Once I have that working, I'll push an extended example that should work on all of the classification tasks.

**Comment by whr94621** [comment]
Any update on this issue>
It would be nice if the implementation of ```BCN``` is released.

**Comment by bmccann** [comment]
AllenNLP has a BCN implementation available: https://github.com/allenai/allennlp/blob/master/allennlp/models/biattentive_classification_network.py. The plan for this repo is just to host CoVe. For training BCN and the other classification tasks, that is a good choice.

**Comment by whr94621** [comment]
@bmccann Thank you !
