### ISSUE TITLE
batch_first should be True when initializing the LSTM?

### ISSUE THREAD

**Issue by wirehack** [salesforce/cove#10]
Here: https://github.com/salesforce/cove/blob/67b690b28a88236b2e0e133ae0bf5c0d0e279171/cove/encoder.py#L34
the LSTM is defined with `batch_first=False` (default value).
However, when you pass the inputs to the LSTM and get outputs from the LSTM, you use `batch_first=True`.
https://github.com/salesforce/cove/blob/67b690b28a88236b2e0e133ae0bf5c0d0e279171/cove/encoder.py#L51-L52

Will this cause inconsistency and generate wrong CoVe vectors?

**Comment by bmccann** [comment]
Hmm, I'm not sure exactly how PyTorch handles this, but I'll change the LSTM to also have batch_first=True to be safe.

**Comment by bmccann** [comment]
3d57c2f Should take care of that.
