### ISSUE TITLE
word embeddings should be fixed during training?

### ISSUE THREAD

**Issue by wirehack** [salesforce/cove#11]
In your paper  Learned in Translation: Contextualized Word Vectors (McCann et. al. 2017), it says 

> We used the CommonCrawl-840B GloVe model for English word vectors, which were completely fixed during training, so that the MT-LSTM had to learn how to use the pretrained vectors for translation.

However, in your code https://github.com/salesforce/cove/blob/67b690b28a88236b2e0e133ae0bf5c0d0e279171/cove/encoder.py#L29-L33
the Glove embeddings are not fixed.

**Comment by bmccann** [comment]
Right, in my paper, I found that the weights should be fixed for better performance. I just wanted to leave this a little more flexible in case others wanted to try fine-tuning on different tasks.
