### ISSUE TITLE
Is there any pre-trained cove from glove avaiable?

### ISSUE THREAD

**Issue by xiezhq-hermann** [salesforce/cove#13]
Or if your could offer a convinent way to train it, it'll be helpful! Since the training is costly, and I don't exactly have a way to verify it quickly.
Thanks!

**Comment by seanliu96** [comment]
I also need pre-trained one.
Thanks!

**Comment by bmccann** [comment]
Yeah! The MTLSTM class here (https://github.com/salesforce/cove/blob/93486571ff6f71816596524735f63f02bb5f2d96/cove/encoder.py) will load in weights that I used. This encoder has already been trained on WMT, so you don't need to train it.

**Comment by xiezhq-hermann** [comment]
Actually, I want to deploy the cove in CNTK framework. Since we could keep the parameters of the hidden layer constant, can I just use the pre-trained `cove(glove(w))` in my embedding? Thus, it's just like the pre-trained word embedding vector.
What do you think about it? Am I right to use it in this way?

**Comment by bmccann** [comment]
I'm not sure that I entirely understand your use case, so if this is totally off-base, let me know: 

Are you considering using a single glove vector as input to the MTLSTM in an effort to get an improved word embedding? The MTLSTM was originally intended to take in a sequence of GloVe  embeddings and output a sequence of contextualized word embeddings, so there isn't a one-to-one mapping between GloVe embeddings and CoVe embeddings in the original setup. I haven't tried using single GloVe embeddings as inputs to the MTLSTM to see whether those outputs are also more useful, so no guarantees that will be helpful to you. That being said, you technically can do that and I would be very curious to see whether that helps in your experiments.

**Comment by xiezhq-hermann** [comment]
Thanks for your reply, it's very helpful.
I don't think the one-to-one mapping is meaningful either. The embedding itself should be generic, and MTLSTM bring more sequence information, which is more corpus-specific.
Thanks again, but do you have any suggestion if I have to use other framework instead of Tensorflow and PyTorch?

**Comment by bmccann** [comment]
A Keras/TensorFlow implementation of the MT-LSTM/CoVe can be found at https://github.com/rgsachin/CoVe.
