### ISSUE TITLE
how to train to get Chinese embeddings.

### ISSUE THREAD

**Issue by skyhiter** [salesforce/cove#17]
hi, 
i want to use CoVe model to Chinese corpus, so i need to train  MT-LSTM using Chinese to English Parallel Corpus.
how can i do that?

thanks.

**Comment by bmccann** [comment]
You can use any open source MT system with Chinese to English parallel data, and the encoder's outputs are a version of CoVe. I used OpenNMT-py for the pretrained weights in this repo.
