### ISSUE TITLE
Error when running get_embed_for_dict.py in OpenNMT-py

### ISSUE THREAD

**Issue by ZeweiChu** [salesforce/cove#20]
When I run get_embed_for_dict.py under OpenNMT-py, I got the following error. I wonder where can I download this file glove.840B.300d.pt ?

python get_embed_for_dict.py data/multi30k.tok.low.src.dict -glove -d_hid 300
Traceback (most recent call last):
  File "get_embed_for_dict.py", line 41, in <module>
    glove = torch.load('glove.840B.300d.pt')
  File "/mnt/cephfs2/asr/users/zewei.chu/anaconda3/envs/py37-torch-0.4/lib/python3.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'glove.840B.300d.pt'

**Comment by bmccann** [comment]
I would recommend using the updated OpenNMT-py (https://github.com/OpenNMT/OpenNMT-py); the version here is no longer maintained for training new versions of CoVe. This repo is really only meant to show how to get access to the pretrained CoVe weights.
