### ISSUE TITLE
How can I train CoVe with my own data？

### ISSUE THREAD

**Issue by imucsliurui** [salesforce/cove#4]
I want to train CoVe with my own train data which contains some sentences without any construction information.

So. How can I make it?
Thank you very much!

**Comment by bmccann** [comment]
I would recommend using something like [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) to train an encoder. I branched off that project a long while back to train the pretrained encoder provided by this repo, but you can use any translation implementation online to get CoVe. Once you've trained the model, just save the encoder and use it as you would the pretrained encoder provided by this repo.
