### ISSUE TITLE
while running "example.py",it has"TypeError: load_vectors() got an unexpected keyword argument 'wv_type'

### ISSUE THREAD

**Issue by aotemandess** [salesforce/cove#7]
Thanks for releasing your code and nice paper!
 I have a question while running "example.py",
 that is"TypeError: load_vectors() got an unexpected keyword argument 'wv_type'".
 Could you please provide with some advice for me ? Thank you very much !

**Comment by ffabulous** [comment]
It seems like the torchtext API has been changed: [torchtext/vocab.py#L94](https://github.com/pytorch/text/blob/master/torchtext/vocab.py#L94)
It should work if you modify test/example.py#L16 as below.
```python
inputs.vocab.load_vectors('glove.840B.300d')
```

**Comment by aotemandess** [comment]
Thank you very much for your reply!
However, when I  modify test/example.py#L16 as below.


inputs.vocab.load_vectors('glove.840B.300d')




it also has an error.







Could you please help me with the question ?
Looking forward to your reply !






At 2017-10-13 15:52:50, "Keunchan Park" <notifications@github.com> wrote:

It seems like the torchtext API has been changed: torchtext/vocab.py#L94
It should work if you modify test/example.py#L16 as below.

inputs.vocab.load_vectors('glove.840B.300d')

**Comment by chickenbestlover** [comment]
It should work if you modify test/example.py#L16 as below. (Worked for me)

`from torchtext.vocab import Glove
inputs.vocab.load_vectors(vectors=GloVe(name='840B', dim=300))`

**Comment by rdslater-tc** [comment]
Small corrrection (but important--capitalize that 'V')

`from torchtext.vocab import GloVe`
`inputs.vocab.load_vectors(vectors=GloVe(name='840B', dim=300))`
